In [11]:

#6
import numpy as np

#creation des tableax (assumant que vous les avez déjà créés)
ones = np.ones((2, 5), dtype=int)
myarray2 = np.arange(4,64,4, dtype=float).reshape(3, 5)

#trouver la transposée
ones_transposed = ones.T
myarray2_transposed = np.transpose(myarray2)

print("Transposée de 'ones':")
print(ones_transposed)

print("\nTransposée de 'myarray2':")
print(myarray2_transposed)


Transposée de 'ones':
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]

Transposée de 'myarray2':
[[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]


In [5]:
#7
#pour diviser le tableau  "myarray2" en 5 tableaux, nous pouvons utiliser numpy.split():
import numpy as np

#creation du tableau(assumant que vous l'avez déjà créé)
#myarray2 - np.array(4,24,4, dtype=float).reshape(1, 5)
myarray2 = np.array([1,2,3,4,5,6,7,8,9,10])
#diviser en 5 sous-tableaux
myarray2A, myarray2B, myarray2C, myarray2D, myarray2E = np.split(myarray2, 5)

print("myarray2A:")
print(myarray2A)
print("myarray2B:")
print(myarray2B)
print("myarray2C:")
print(myarray2C)
print("myarray2D:")
print(myarray2D)
print("myarray2E:")
print(myarray2E)

myarray2A:
[1 2]
myarray2B:
[3 4]
myarray2C:
[5 6]
myarray2D:
[7 8]
myarray2E:
[ 9 10]


In [6]:
#pour diviser le tableau "zeros" aux indices 2,5,7,8, nous pouvons utiliser le decoupage :
zeros = np.zeros(10)

#diviser au indices specifies 
zerosA = zeros[:2]
zerosB = zeros[2:5]
zerosC = zeros[5:7]
zerosD = zeros[7:8]

print("\nzerosA:")
print(zerosA)
print("\nzerosB:")
print(zerosB)
print("\nzerosC:")
print(zerosC)
print("\nzerosD:")
print(zerosD)


zerosA:
[0. 0.]

zerosB:
[0. 0. 0.]

zerosC:
[0. 0.]

zerosD:
[0.]


In [7]:
#pour concatener les tableaux "myarray2A","myarray2B" et "myarray2C" en un tableau ayant 3lignes et 3colonnes

myarray2_concatenated = np.concatenate((myarray2A, myarray2B, myarray2C),axis=0)

print("\nTableau résultant de la concatenation:")
print(myarray2_concatenated)



Tableau résultant de la concatenation:
[1 2 3 4 5 6]


In [3]:
#8
import numpy as np
#creer le tableau 2D avec arange()
myarray4 = np.arange(-1,14*3*0.25-1,0.25).reshape((14,3))
#diviser le tableau en 3 parties égales
part_size = myarray4.shape[0] // 3
part1 = myarray4[:part_size]
part2 = myarray4[part_size:2*part_size]
part3 = myarray4[2*part_size:]
#imprimer les resultats
print("partie 1 :\n", part1)
print("partie 2 :\n", part2)
print("partie 3 :n\n",part3)

partie 1 :
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]]
partie 2 :
 [[2.   2.25 2.5 ]
 [2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]]
partie 3 :n
 [[5.   5.25 5.5 ]
 [5.75 6.   6.25]
 [6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]


In [2]:
#9
import numpy as np
#creation du tableau (assumant que vous l'avez déjà crée)
myarray4 = np.arange(-1,14*0.25-1,0.25).reshape(1, 14)

#somme de tous les éléments
total_sum = np.sum(myarray4)

print("somme de tous les éléments de 'myarray4':", total_sum)



somme de tous les éléments de 'myarray4': 8.75


In [3]:
row_sum = np.sum(myarray4)

print("somme de tous les éléments de 'myarray4':", total_sum)

somme de tous les éléments de 'myarray4': 8.75
